language: python
python:
  - '3.4'
  - "3.5"

install:
  - pip install .
  - pip install coverage pytest pytest-cov coveralls

script:
  - export VERIPRESS_INSTANCE_PATH=$(pwd)/veripress_tests/instance
  - coverage run --source veripress -m py.test veripress_tests

after_success:
  coveralls