language: python
python:
  - '3.4'
  - "3.5"

env:
  global:
    - GIT_NAME: "Richard Chien"
    - GIT_EMAIL: richardchienthebest@gmail.com

before_install:
  - nvm install 4

install:
  - pip install .
  - pip install -r test-requirements.txt

script:
  - export VERIPRESS_INSTANCE_PATH=$(pwd)/veripress_tests/instance
  - coverage run --source veripress -m py.test veripress_tests
  - export VERIPRESS_INSTANCE_PATH=$(pwd)/veripress_demo_instance
  - veripress generate --app-root /demo/
  - export VERIPRESS_INSTANCE_PATH=$(pwd)/veripress_docs
  - veripress generate --app-root /docs/
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [[ $TRAVIS_BRANCH =~ ^v[0-9.]+$ ]]; then echo ${TRAVIS_BRANCH#v}; else echo $TRAVIS_BRANCH; fi`
  - docker build -f Dockerfile -t $DOCKER_REPO:$TAG .

after_success:
  - coveralls
  - chmod +x after-travis-ci-success.sh && ./after-travis-ci-success.sh